import { tmpdir } from "node:os"
import type { UserConfig } from "@11ty/eleventy"
import { build } from "esbuild"
import htmlMinifier from "html-minifier-terser"
// import { isValidElement } from "preact"
// import { render } from "preact-render-to-string"
import requireFromString from "require-from-string"
import { read } from "to-vfile"
import { matter } from "vfile-matter"
import { remarkPlugins, rehypePlugins } from "../components/markdown/markdown.config.ts"
import { isBuild, isPreview } from "./mode.ts"

export function markupPlugin(uc: UserConfig): void {
  uc.addTemplateFormats("11ty.js")
  uc.addExtension("tsx", {
    key: "11ty.js"
  })

  uc.addTemplateFormats("mdx")
  uc.addExtension("mdx", {
    outputFileExtension: "html",
    compile(_: string, f: string) {
      return async () => {
        const { compile } = await import("@mdx-js/mdx")
        const r = await build({
          entryPoints: [f],
          format: "cjs",
          outdir: tmpdir(),
          write: false,
          plugins: [
            {
              name: "mdx",
              setup(build) {
                build.onLoad({ filter: /\.mdx?$/ }, async (...a) => {
                  // todo: explain why this lib
                  // because vfile is already a third-party dependency.
                  // https://www.npmjs.com/package/gray-matter
                  let vf = await read(f)
                  matter(vf, { strip: true })
                  vf = await compile(vf.value, {
                    jsxImportSource: "preact",
                    rehypePlugins,
                    remarkPlugins
                  })
                  return {
                    contents: vf.value
                  }
                })
              }
            }
          ]
        })
        const m = requireFromString(r.outputFiles[0].text)
        return m.default()
        // todo: add validation and error handling.
        // const p = m.default()
        // if (isValidElement(p)) {
        //   if (data.layout && (data.layout.endsWith(".jsx") || data.layout.endsWith(".tsx"))) {
        //     return p
        //   }
        //   // todo: delete it, thrown an error.
        //   return render(p)
        // }
        // console.log(data.page)
        // console.log("warn")
        // return ""
      }
    }
  })
}

/**
 * @param c The markup to be transformed.
 * @returns The transformed markup.
 */
export async function transformMarkup(c: string): Promise<string> {
  const minify = isBuild() || isPreview()
  if (!minify) {
    return c
  }
  return htmlMinifier.minify(c, {
    collapseBooleanAttributes: true,
    collapseWhitespace: true,
    decodeEntities: true,
    includeAutoGeneratedTags: false,
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeRedundantAttributes: true,
    sortAttributes: true
  })
}
