<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl" %>

<h1>
    <span class="hdr">How to integrate online editors into your own website on Node.js</span>
</h1>

<h2>Overview</h2>
<p class="dscr">
    This example will help you integrate ONLYOFFICE Docs into your web application on Node.js.
</p>

<div class="note">
    It is intended for testing purposes and demonstrating functionality of the editors.
    <b>DO NOT</b> use this integration example on your own server without proper code modifications.
    In case you enabled the test example, disable it before going for production.
</div>

<h2 id="security" class="copy-link">Important security info</h2>
<p>Please keep in mind the following security aspects when you are using test examples:</p>
<ul>
    <li>There is no protection of the storage from unauthorized access since there is no need for authorization.</li>
    <li>There are no checks against parameter substitution in links, since the parameters are generated by the code according to the pre-arranged scripts.</li>
    <li>There are no data checks in requests of saving the file after editing, since each test example is intended for requests only from ONLYOFFICE Docs.</li>
    <li>There are no prohibitions on using test examples from other sites, since they are intended to interact with ONLYOFFICE Docs from another domain.</li>
</ul>

<h2 id="Windows" class="copy-link">For Windows</h2>
<h2 id="win-1" class="copy-link"><span class="style_step">Step 1. </span>Install ONLYOFFICE Docs</h2>
<p>Download and install ONLYOFFICE Docs (packaged as Document Server):</p>
<div class="list-buttons">
    <a class="button" href="https://www.onlyoffice.com/download-docs.aspx?from=api#docs-developer" target="_blank">Get ONLYOFFICE Docs</a>
</div>
<p>See the detailed guide to learn how to <a target="_blank" href="https://helpcenter.onlyoffice.com/installation/docs-developer-install-windows.aspx?from=api_nodejs_example">install ONLYOFFICE Docs for Windows</a>.</p>

<h2 id="win-2" class="copy-link"><span class="style_step">Step 2. </span>Download the Node.js code for the editors integration<span class="copy-link" title="Click to get link"></span></h2>
<p>Download the <a href="<%= Url.Action("demopreview") %>">Node.js example</a> from our site.</p>
<p>
    To connect the editors to your website, specify the path to the editors installation and the path to the storage folder in the <em>config/default.json</em> file:
</p>
<pre class="commandline">
"storageFolder": "./files"
"storagePath": "/files"
"siteUrl": "https://documentserver/"
</pre>

<p>where the <b>documentserver</b> is the name of the server with the ONLYOFFICE Docs installed, the <b>storageFolder</b> and <b>storagePath</b> are the paths where files will be created and stored.
You can set an absolute path. For example, <em>D:\\folder</em>. Please note that on Windows OS the double backslash must be used as a separator.</p>
<p>If you want to experiment with the editor configuration, modify the <a href="<%= Url.Action("advanced") %>">parameters</a> in the <em>\views\editor.ejs</em> file.</p>

<h2 id="win-3" class="copy-link"><span class="style_step">Step 3. </span>Install Node.js environment</h2>
<p>
    Install the <b>node.js</b> environment which is going to be used to run the Node.js project.
    Please follow the link at the <a href="https://nodejs.org/en/download/" target="_blank">official website</a> choosing the correct version for your Windows OS (32-bit or 64-bit).
</p>

<h2 id="win-4" class="copy-link"><span class="style_step">Step 4. </span>Run the Node.js code</h2>
<p>We will run the code in Node.js runtime environment and will interact with it using the <b>command line interface (cmd)</b>.</p>

<ol>
    <li>Launch the <b>Command Prompt</b> and switch to the folder with the Node.js project code, for example:
        <div class="commandline">cd /d "C:\Node.js Example"</div>
    </li>
    <li>Node.js comes with a package manager, <b>node package manager (npm)</b>, which is automatically installed along with Node.js.
        To run the Node.js code, install the project modules using the following <em>npm</em> command:
        <div class="commandline">npm install</div>
        <p>A new <em>node_modules</em> folder will be created in the project folder.</p>
    </li>
    <li>Run the project using the <b>Command Prompt</b>:
        <div class="commandline">node bin/www</div>
    </li>
    <li>See the result in your browser using the address:
        <div class="commandline">http://localhost:3000</div>
    </li>
</ol>

<h2 id="win-5" class="copy-link"><span class="style_step">Step 5. </span>Check accessibility</h2>
<p>
    In case the example and ONLYOFFICE Docs are installed on different computers, make sure that your server with the example installed has access to the ONLYOFFICE Docs with the address which you specify instead of <b>documentserver</b> in the configuration files.
    Make sure that the ONLYOFFICE Docs in its turn has access to the server with the example installed with the address which you specify instead of <b>example.com</b> in the configuration files.
</p>

<p>If you integrated the editors successfully the result should look like the <a href="<%= Url.Action("demopreview") %>#DemoPreview">demo preview</a> on our site.</p>

<h2 id="Linux" class="copy-link">For Linux</h2>
<h2 id="linux-1" class="copy-link"><span class="style_step">Step 1. </span>Install ONLYOFFICE Docs</h2>
<p>Download and install ONLYOFFICE Docs (packaged as Document Server):</p>
<div class="list-buttons">
    <a class="button" href="https://www.onlyoffice.com/download-docs.aspx?from=api#docs-developer" target="_blank">Get ONLYOFFICE Docs</a>
</div>
<p>See the detailed guide to learn how to <a target="_blank" href="https://helpcenter.onlyoffice.com/installation/docs-developer-install-ubuntu.aspx?from=api_nodejs_example">install ONLYOFFICE Docs for Linux</a>.</p>

<h2 id="linux-2" class="copy-link"><span class="style_step">Step 2. </span>Install the prerequisites and run the website with the editors</h2>
<ol>
    <li>Install <b>Node.js</b>:
        <div class="commandline">curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -</div>
        <div class="commandline">sudo apt-get install -y nodejs</div>
    </li>
    <li>Download the archive with the Node.js example and unpack the archive:
        <div class="commandline">wget https://github.com/ONLYOFFICE/document-server-integration/releases/latest/download/Node.js.Example.zip</div>
        <div class="commandline">unzip Node.js.Example.zip</div>
    </li>
    <li>Change the current directory for the project directory:
        <div class="commandline">cd Node.js\ Example/</div>
    </li>
    <li>Install the dependencies:
        <div class="commandline">npm install</div>
    </li>
    <li>Edit the <em>config/default.json</em> configuration file.
        Specify the name of your local server with the ONLYOFFICE Docs installed.
        <div class="commandline">nano config/default.json</div>
        <p>Edit the following lines:</p>

        <pre>
"storageFolder": "./files"
"storagePath": "/files"
"siteUrl": "https://documentserver/"
</pre>

        <p>where the <b>documentserver</b> is the name of the server with the ONLYOFFICE Docs installed, the <b>storageFolder</b> and <b>storagePath</b> are the paths where files will be created and stored.
        Please note that you must have read and write permissions to the folder. If you do not have them, please use the next command:</p>
        <pre>
sudo chmod -R ugo+rw /{path}
</pre>
    </li>
    <li>Run the project with Node.js:
        <div class="commandline">node bin/www</div>
    </li>
    <li>See the result in your browser using the address:
        <div class="commandline">http://localhost:3000</div>
    </li>
</ol>

<h2 id="linux-3" class="copy-link"><span class="style_step">Step 3. </span>Check accessibility</h2>
<p>
    In case the example and ONLYOFFICE Docs are installed on different computers, make sure that your server with the example installed has access to the ONLYOFFICE Docs with the address which you specify instead of <b>documentserver</b> in the configuration files.
    Make sure that the ONLYOFFICE Docs in its turn has access to the server with the example installed with the address which you specify instead of <b>example.com</b> in the configuration files.
</p>

<p>If you integrated the editors successfully the result should look like the <a href="<%= Url.Action("demopreview") %>#DemoPreview">demo preview</a> on our site.</p>
