<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl" %>

<h1>
    <a class="up" href="<%= Url.Action("config/") %>"></a>
    <span class="hdr">Document</span>
</h1>

<div class="header-gray">Description</div>
<p class="dscr">The document section allows to change all the parameters pertaining to the document (title, url, file type, etc.).</p>

<div class="header-gray">Parameters</div>
<table class="table">
    <colgroup>
        <col class="table-name" />
        <col />
        <col class="table-type" />
        <col class="table-example" />
    </colgroup>
    <thead>
        <tr class="tablerow">
            <td>Name</td>
            <td>Description</td>
            <td>Type</td>
            <td>Example</td>
        </tr>
    </thead>
    <tbody>
        <tr class="tablerow">
            <td id="fileType" class="copy-link">fileType<span class="required">*</span></td>
            <td>
                Defines the type of the file for the source viewed or edited document.
                Must be lowercase.
                The following file types are available: <em>.csv, .djvu, .doc, .docm, .docx, .docxf, .dot, .dotm, .dotx, .epub, .fb2, .fodp, .fods, .fodt, .htm, .html, .mht, .odp, .ods, .odt, .oform, .otp, .ots, .ott, .oxps, .pdf, .pot, .potm, .potx, .pps, .ppsm, .ppsx, .ppt, .pptm, .pptx, .rtf, .txt, .xls, .xlsb, .xlsm, .xlsx, .xlt, .xltm, .xltx, .xml, .xps</em>.
            </td>
            <td>string</td>
            <td>"docx"</td>
        </tr>
        <tr>
            <td id="key" class="copy-link">key<span class="required">*</span></td>
            <td>
                Defines the unique document identifier used by the service to recognize the document.
                In case the known key is sent the document will be taken from the cache.
                Every time the document is edited and saved, the key must be generated anew.
                The document url can be used as the <b>key</b> but without the special characters and the length is limited to 128 symbols.
            </td>
            <td>string</td>
            <td>"Khirz6zTPdfd7"</td>
        </tr>
        <tr class="tablerow tablerow-note">
            <td colspan="4">
                <div class="note">The key characters can be used: <b>0-9</b>, <b>a-z</b>, <b>A-Z</b>, <b>-._=</b>.
                The maximal key length is <b>128</b> characters.</div>
            </td>
        </tr>
        <tr class="tablerow">
            <td id="referenceData" class="copy-link">referenceData</td>
            <td>
                Defines an object that is generated by the integrator to uniquely identify a file in its system:
                <ul>
                    <li>
                        <b>fileKey</b> - the unique document identifier used by the service to get a link to the file.
                        It must not be changed when the document is edited and saved (i.e. it is not equal to the <a href="#key">document.key</a> parameter),
                        <br />
                        <b>type</b>: string,
                        <br />
                        <b>example</b>:  "BCFA2CED";
                    </li>
                    <li>
                        <b>instanceId</b> - the unique system identifier. If the data was copied from a file on one system, and inserted into a file on another,
                        then pasting by link will not be available and there will be no corresponding button in the context menu,
                        <br />
                        <b>type</b>: string,
                        <br />
                        <b>example</b>:  "https://example.com".
                    </li>
                </ul>
            <td>object</td>
            <td>{
    "fileKey": "BCFA2CED",
    "instanceId": "https://example.com"
}</td>
        </tr>
        <tr class="tablerow">
            <td id="title" class="copy-link">title<span class="required">*</span></td>
            <td>
                Defines the desired file name for the viewed or edited document which will also be used as file name when the document is downloaded.
                The length is limited to 128 symbols.
            </td>
            <td>string</td>
            <td>"Example Document Title.docx"</td>
        </tr>
        <tr class="tablerow">
            <td id="url" class="copy-link">url<span class="required">*</span></td>
            <td>
                Defines the absolute URL where the source viewed or edited document is stored.
                Be sure to add a <a href="<%= Url.Action("security") %>">token</a> when using local links.
                Otherwise, an error will occur.
            </td>
            <td>string</td>
            <td>"https://example.com/url-to-example-document.docx"</td>
        </tr>
    </tbody>
</table>
<div class="mobile-content"></div>

<span class="required-descr"><span class="required">*</span><em> - required field</em></span>

<div class="header-gray">Example</div>
<pre>
var docEditor = new DocsAPI.DocEditor("placeholder", {
    "document": {
        "fileType": "docx",
        "key": "Khirz6zTPdfd7",
        "referenceData": {
            "fileKey": "BCFA2CED",
            "instanceId": "https://example.com"
        },
        "title": "Example Document Title.docx",
        "url": "https://example.com/url-to-example-document.docx",
    },
    ...
});
</pre>
<p>
    Where the <b>example.com</b> is the name of the server where <b>document manager</b> and <b>document storage service</b> are installed.
    See the <a href="<%= Url.Action("howitworks") %>">How it works</a> section to find out more on Document Server service client-server interactions.
</p>
